### PR TITLE
Added REST apis for adding/delete and update assignments

### PR DESCRIPTION
**Pull request by emranarsala**

### CODE REVIEW

**Comment by 1rvine** [comment]
Great work Emran! Everything seemed to work.

**Comment by emranarsala** [comment]
I added REST apis where instructors can add assignments to a course if the course exists and the instructor teaches it.

**Comment by emranarsala** [comment]
I added REST apis where instructors can edit assignment names for the courses that they teach.

**Comment by emranarsala** [comment]
I added REST apis where instructors can delete assignments from their courses if it has no grades.

**Comment by emranarsala** [comment]
I added Junit test cases to test the REST apis for adding/deleting and updating names.

**Pull request merged**
